name: Notify Telegram on Push

on:
  push:
    branches:
      - main  # You can change this to the branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage \
        -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
        -d text="New push to the repository: ${{ github.repository }} by ${{ github.actor }}. Commit message: ${{ github.event.head_commit.message }
